apiVersion: v1
kind: "Template"
metadata:
  name: logging-dev-build-template
  annotations:
    description: "Template for creating local builds of logging components from source."
    tags: "infrastructure"
labels:
  logging-infra: development
  provider: openshift
  component: development
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: logging-fluentd
    name: logging-fluentd
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: logging-fluentd
    name: logging-fluentd
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: logging-fluentd:latest
    resources: {}
    source:
      contextDir: fluentd
      git:
        uri: ${LOGGING_FORK_URL}
        ref: ${LOGGING_FORK_BRANCH}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: Dockerfile.centos7
      type: Docker
    triggers:
    - type: ConfigChange
    - type: ImageChange
parameters:
-
  description: 'URL for origin-aggregated-logging fork'
  name: LOGGING_FORK_URL
  value: https://github.com/openshift/origin-aggregated-logging
-
  description: 'branch for origin-aggregated-logging fork'
  name: LOGGING_FORK_BRANCH
  value: master
