source 'https://rubygems.org'

gem 'benchmark-ips', :group => :test, :require => nil
gem 'codeclimate-test-reporter', :group => :test, :require => nil
gem 'rubocop', require: false

# Specify your gem's dependencies in fluent-plugin-add.gemspec
gemspec
